---
- field: LAN966X_FW_CONF_MMC_CLK_RATE
  size: 32
  value: 52000000
- field: LAN966X_FW_CONF_MMC_BUS_WIDTH
  size: 8
  value: 2      # MMC_BUS_WIDTH_8
- field: LAN966X_FW_CONF_QSPI_CLK
  size: 8
  value: 30
...
